### ISSUE TITLE
Component update: checkbox

### ISSUE THREAD

**Issue by emaurer11** [Automattic/vip-design-system#237]
We need a couple of minor styling tweaks to this component:
- remove the gray outline from selected state
- make sure we're using the checkmark icon from Figma (this matches what we're using on the toggle component)
- make sure all of the colors are referencing the right design system color tokens (see Figma)
- list item text accompanying a checkbox should use normal body text styles (secondary text color, regular font weight)

There are no stories in Storybook showing what an isolated checkbox component looks like. Can we add a story showing just the input (no text, not in a list) as part of this update, too?

[Figma spec](https://www.figma.com/file/jcGe2KIAlh2PxaAZ5liYWi/Productive-Components?type=design&node-id=8082%3A17773&mode=design&t=NSkSW6dzTofmH9a5-1)

**Comment by djalmaaraujo** [comment]
@emaurer11 We always had an example on Storybook: http://localhost:6006/?path=/docs/form-checkbox--docs

**Comment by emaurer11** [comment]
@djalmaaraujo the link you sent ⬆️ isn't working for me. Would you mind sending it again?

**Comment by djalmaaraujo** [comment]
@emaurer11 Regarding "There are no stories in Storybook showing what an isolated checkbox component looks like. Can we add a story showing just the input (no text, not in a list) as part of this update, too?"

We are explicitly doing this because there should not be a Checkbox or Radio without a label. This is not accessible. We could have hidden labels pointing to it, but we can revisit the storybook later if needed.
